### ISSUE TITLE
Number of individuals in DHS shelter system by last known address

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-equitable-development-tool#112]
Description: Number of individuals in DHS shelter by last known address
Report totals for each community district. For records with no known community district, only report for Borough. "by community district based on last known address of such individuals or families, where known." 

Logic:

Source(s): [Associated Address by Borough and Community District | NYC Open Data (cityofnewyork.us)](https://data.cityofnewyork.us/Social-Services/Associated-Address-by-Borough-and-Community-Distri/ur7y-ziyb/data)

Year(s):
- [x] 3/31 reporting for 2018
- [x] 3/31 reporting for 2020

Geographies:
- [x] PUMA
- [x] Borough
- [x] City

Race and ethnicity breakdown: No
Denominator:

SME: HPD

Questions:

Roadblocks:

**Comment by SashaWeinstein** [comment]
How about `DHS_shelter_2018` and `DHS_shelter_2020` as column names?
