### ISSUE TITLE
Educational outcomes: ELA

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-equitable-development-tool#113]
Description: percent of 3rd-8th grade students that are ELA  proficient by where students live

WWL Figure 5.75. Use WWL data for EDDT launch. DOE will supply annual data for future years.Cannot report last two years because of COVID.  Waiting on link/folder of that data from DOE

Logic:

Source(s): DOE; HPD 2017-2018 WWL data - spreadsheet [here](https://nyco365.sharepoint.com/:x:/r/sites/NYCPLANNING/civic-engagement-studio/_layouts/15/Doc.aspx?sourcedoc=%7B3A897425-085E-4D69-9089-085A6366B421%7D&file=NTA_data_prepared_for_ArcMap_wCodebook.xlsx&action=default&mobileredirect=true)

Year(s):
- [ ] 2017/2018

Geographies:
- [ ] PUMA
- [ ] Borough
- [ ] City

Race and ethnicity breakdown: Yes
Denominator: total students

SME: Chad

Questions:

Roadblocks:
Field name convention: `edu_ela`

**Comment by Cwilliams-1** [comment]
Columns to be divided from 5_StudentPerformance tab in linked spreadsheet: H/B(All Students); I/C(Asian); J/D(Black); K/E(Hispanic); L/F(Other); M/G(White)


[https://nyco365.sharepoint.com/:x:/r/sites/NYCPLANNING/civic-engagement-studio/Shared%20Documents/03.%20Working%20Materials/03.%20%20Equity%20and%20Displacement%20Vulnerability/HPD-DCP%20EDDT%20Coordination/02.%20Indicators/EDDT%20QOL%20Indicators/DOE%20WWL%20Data/DOE%20Access%20to%20Opportunity%20Files/DOE%20Clean%20Data/Request%204%20and%205%20-%20Location%20of%20Proficient%20Schools%20and%20NTA%20Outcomes/NTA_data_prepared_for_ArcMap_wCodebook.xlsx?d=w3a897425085e4d699089085a6366b421&csf=1&web=1&e=JhPZXB]

**Comment by td928** [comment]
@Cwilliams-1 Hey Chad is the right understanding that this is reported on NTA level instead of PUMA and we are not doing any translating for geographies?

**Comment by td928** [comment]
@AmandaDoyle My bad. I now see that there are columns for just 4th grade and the other ones I assume are for 3rd to 8th grade.

Question for NTA vs PUMA remain

**Comment by AmandaDoyle** [comment]
@td928  The spreadsheet [Census Tract/ NTA/PUMA Equivalencies](https://www1.nyc.gov/assets/planning/download/office/data-maps/nyc-population/census2010/nyc2010census_tabulation_equiv.xlsx) from [here](https://www1.nyc.gov/site/planning/data-maps/nyc-population/geographic-reference.page) has the crosswalk between NTA and PUMA.  This spreadsheet should def be incorporated into a workflow as it will be reused.

Values for NTAs that roll up into the same PUMA will need to be summed.

**Comment by AmandaDoyle** [comment]
@td928 regarding field names, using the [wiki](https://github.com/NYCPlanning/db-equitable-development-tool/wiki/New-data-pipeline:-field-naming-convention) as a guide, the field name for this indicator could be
`education_ela_pct`  
`education_ela_pct_wnh`
`education_ela_pct_bnh`  
etc.
cc @NYCPlanning/data-engineering  for input
