### ISSUE TITLE
Standardize weights and replicate weights columns

### ISSUE THREAD

**Issue by SashaWeinstein** [NYCPlanning/db-equitable-development-tool#13]
All data from ingestion process should have weight col named `fw` and replicate weights `rw1-80`.

**Comment by mbh329** [comment]
Sasha advised that we create a script that keeps the replicate weight column names across the HVS and PUMS data the same (for consistency when dealing with weights: Raw Columns - HVS = fw1-80, PUMS =  PWGTP1-80).

**Comment by SashaWeinstein** [comment]
@mbh329 where do we stand on this improvement?

**Comment by mbh329** [comment]
@SashaWeinstein I haven't worked on it recently with all the pluto stuff we had been doing last week

**Comment by mbh329** [comment]
if its priority, I can pick it up first thing tomorrow

**Comment by SashaWeinstein** [comment]
No don't worry about it, it's not a priority. Did you push any code on this issue?

**Comment by mbh329** [comment]
No, I was developing in a ipynb locally
