### ISSUE TITLE
median-age-MOE/CV in 2015-2019 and 2008-2012 ACS PUMS data is 0 at the borough level aggregation

### ISSUE THREAD

**Issue by mbh329** [NYCPlanning/db-equitable-development-tool#138]
Going through spot checks and noticed that there are no calculated `age-median-MOE`, `age-median-CV` for the 2015-2019 data for 3/5 boroughs and no calculated `age-median-MOE` or `age-median-CV` for any borough in the 2008-2012 data.  This is also happening at the citywide level in the 2008-12 data (which makes sense seeing as there is no calculation at the borough level). I will dig into the citywide median aggregations for the 2015-19 data now.

Example of the Demographic Median Aggregation at the borough level for 2015-19 ACS PUMS Data:
<img width="854" alt="Screen Shot 2022-02-17 at 1 40 30 PM" src="https://user-images.githubusercontent.com/41444592/154549877-5177b4e5-a4c7-4fa4-943c-1407c901918f.png">

**Comment by mbh329** [comment]
Running `agg19 = PUMSMedianDemographics(year = 2019, geo_col = "borough", requery = True)` in ipython

**Comment by SashaWeinstein** [comment]
Oh I see when you say none you mean it's all zeros. I originally thought you meant NaN. 
Going to compare against Erica's file of demographics indicators based off 2000 census

**Comment by SashaWeinstein** [comment]
Compared against Erica's numbers. In her numbers MOE and CV for median age of total pop per borough are .1 except for bronx CV which is .2. Which is not so conclusive
But then I looked at median age by race, where for example 3/5 boroughs have 0 CV and MOE for median age for asians where in Erica's numbers the CV for this indicator range from .007 to .018. And the MOE range from .4 to 2.2. 
So I think we are doing something wrong. I guess it's plausible that survey response rates or the capacity of the census to get a representative sample improved but that seems unlikely. 
I'm checking out that link you posted in the teams chat now
