### ISSUE TITLE
2000 Demographic data review

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-equitable-development-tool#193]
Review of 2000 PUMS data at PUMA level output

- [x] Population under 16 data points are missing
- [x] Order of columns should match the 0812 and 1519 outputs.  It won't be exact, but should be same subcategory order (i.e. pop, lep, fb, age)

Values are correct.

**Comment by mbh329** [comment]
@SashaWeinstein Let me know when you are back online and we can chat about these, the internal review files and the script output the popu16 data points - I could be wrong but I thought the column order is done in the external review process or should i reorder them in the census pums script?

**Comment by SashaWeinstein** [comment]
Chatted with Max and I will address both of these issues and send a message in teams when the action with these issues addressed is up. 

Once we have an output we are happy with I can work on QOL or write up the pull request to merge this work into dev. Let me know which is higher priority @AmandaDoyle
