### ISSUE TITLE
Rename QOL Access to car denominator column and reorder QOL access to broadband/access to car columns

### ISSUE THREAD

**Issue by mbh329** [NYCPlanning/db-equitable-development-tool#202]
Couple things to do to get the QOL indicators out to OSE:
- [x] Update the QOL Access to Transit: car commute column from `access_carcommute_workers_` to `access_workers16pl_` as discussed in pull req #198 
- [x] Reorder the columns in QOL Access to broadband and Access to Transit:car commute to match race crosstab conventions that have already been established

**Comment by td928** [comment]
hey looks good Max. Let me know if you have a branch pointed at this issue

**Comment by mbh329** [comment]
202-fix-qol-access-broadband-carcommute @td928 @SashaWeinstein

**Comment by SashaWeinstein** [comment]
Sorted both dataframes, let me know what you all think

**Comment by td928** [comment]
I took a look at the branch and I think both work look good to me. Is there a pull request being created right now for this?

**Comment by mbh329** [comment]
Let me take a quick look as well, I have not started a pull req for this issue @td928 @SashaWeinstein
