### ISSUE TITLE
Housing production - add measure tokens

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-equitable-development-tool#238]
Add measure tokens for the following set of indicators:
- [x] units_INCOME_newconstruction series
- [x] units_INCOME_preservation

**Comment by td928** [comment]
@AmandaDoyle I think this work is included in the branch I merged in yesterday. I also made some change to the other two indicators in this category essentially just adding `_count` token to them. Please check branch #231 citywide internal review files for a sample of output and let me know if anything still missing from this. Thank you!
