### ISSUE TITLE
Change in units

### ISSUE THREAD

**Issue by SashaWeinstein** [NYCPlanning/db-equitable-development-tool#26]
First non-PUMS indicator to be added. Will come from EDM-publishing space or BYTES

**Comment by AmandaDoyle** [comment]
Description
- Ingest housing database from TBD
- Calculate the following at the PUMA, Brough, and City level
1. Total net change
2. Total net change from new buildings
3. Total net change from demolitions
4. Total net change from alterations that increased the number of units
5. Total net change from alterations that decreased the number of units

Outstanding questions
- Are we just considering class A units?
- Are we only counting complete jobs?  
- Does this need to be reported as percent?  If so, what is the denominator?

**Comment by levysamu** [comment]
Only thing that I will add is that you should filter out inactive records as well. Sometimes "complete" jobs will be duplicates and we filter them out in the inactive column. It should be a small universe of records.

**Comment by td928** [comment]
a new commit is made to change projects included in the script to only post 2010 which is under this commit [8a8ba2f](https://github.com/NYCPlanning/db-equitable-development-tool/commit/8a8ba2f6fba225f2e3eda160d0c6828750f75eac)
