### ISSUE TITLE
Add Pop in NYCHA housing to Housing Security output

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-equitable-development-tool#260]
Add the following data points to the Housing Security output.
- Total Population (Public Housing and RAD)
     - Count
     - Percent
     - By Race and ethnicity
- 2020 Census Total Pop values, which are in Demographic output.  OSE cannot cross reference tables. 

Logic:

- Total Population (Public Housing and RAD) by race and ethnicity.  Logic is to sum Public Housing White and RAD White, for example
- Denominator to calculate the percent is the 2020 Census Total Pop values, which are in Demographic output

Data source: 
[Equitable Development Data Tool - Displacement Risk Index 2-8-2022 (1).xlsx](https://github.com/NYCPlanning/db-equitable-development-tool/files/8393100/Equitable.Development.Data.Tool.-.Displacement.Risk.Index.2-8-2022.1.xlsx)
This is used for other existing data points.

For reference,the lower box is where these data are being mapped
<img width="687" alt="Screen Shot 2022-03-31 at 3 07 17 PM" src="https://user-images.githubusercontent.com/5611960/161148846-01ec23ba-1d53-4c71-bdbc-5857ecfdd21d.png">

**Comment by td928** [comment]
@AmandaDoyle does the columns naming `rad_pop` and `public_housing_pop` make sense to you for those indicators?

**Comment by AmandaDoyle** [comment]
@td928 there is only one "one column" (i.e. nycha_tenants could be a good name) then nycha_tenants_anh for example.  We need to sum the two columns Public Housing and RAD to get the total number of NYCHA tenants by race and ethnicity.  Ping me if you'd like to hop on a call to talk this through.

**Comment by SashaWeinstein** [comment]
I believe this is the first instance of us referencing a particular data point in two different categories? Curious to see how you do this Te. My first thought is to call the decennial census accessor and take the correct column from the dataframe it returns. Of course there are multiple good ways to do it

**Comment by td928** [comment]
yep this is my thought process too. The census accessor is pretty much what we need apart from the extra pct columns and easy to get rid off. Then hopefully the percent calculation for each race category is straightforward

**Comment by AmandaDoyle** [comment]
@td928 thanks for flagging.  I may be mistaken, but do we have a resource to map 2010 PUMAS to 2020 PUMAS?  If so, we should use that.  If not, then we can do a 1:1 join and leave fields where there is no match blank and flag it to OSE and leave it as a future improvement.

**Comment by td928** [comment]
Okay maybe I am not aware of it. Loop in @mbh329 and @SashaWeinstein for help, do we have a mapper from 2010 pumas to 2020 pumas?

**Comment by SashaWeinstein** [comment]
We haven't done anything with 2020 PUMAs. We looked at 2000 and 2010 PUMAs for our own ACS PUMS pipeline that we didn't end up using. Don't know anything about 2020 PUMAs, but could there be another reason they are left off source data?

**Comment by SashaWeinstein** [comment]
This [site from dcp population](https://storymaps.arcgis.com/stories/0e4344ea8fec44ee89f881e705edf206) maps old to new geographies. I remember talking with I think Joel about it but I don't remember what the conclusions were. It doesn't map from 2010 to 2020 PUMAs so maybe they are the same?

**Comment by mbh329** [comment]
@td928 did they leave off the pumas in the xlsx for public housing tenants because there just aren't aren't any nycha buildings?

**Comment by levysamu** [comment]
Hey all, I'm not sure why you are referencing 2020 PUMAs here. The NYCHA data is using 2010 PUMAs and the demographic tables are using 2020 census data mapped to 2010 PUMAs already. There should not be anything to calculate or convert. Let me know if we need to jump on a call quickly.

**Comment by td928** [comment]
Okay great @levysamu we had concerned about the population and NYCHA is not consistent on geographies. As long as they are all the same then it is perfect for our purpose and this should be ready to be review soon.

**Comment by td928** [comment]
okay this is now closed with #266 merged in and will have new output for SME to look at.
