### ISSUE TITLE
Public safety: Assault indicator missing from QOL outputs

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-equitable-development-tool#261]
Original issue is here #94
Goal: Add data point to output

**Comment by TylerMatteo** [comment]
It looks like we're also missing pedestrian hospitalizations - `safety_pedhospital`

**Comment by SashaWeinstein** [comment]
Found the issue, the two accessors weren't in the QOL list in all accessors module. Should I re-run the QOL exports with these two added?

**Comment by SashaWeinstein** [comment]
@AmandaDoyle sorry should have tagged before

**Comment by AmandaDoyle** [comment]
@SashaWeinstein  Yes, let's rerun QOL with the accessors added.
