### ISSUE TITLE
Add in percent fields for units_payingrent in Housing Security

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-equitable-development-tool#269]
Add in percent fields for units_payingrent in Housing Security

**Comment by SashaWeinstein** [comment]
The pct and pct moe fields in the source data are always null for "HUPRt"

**Comment by AmandaDoyle** [comment]
Okay - let me look into this before we address

**Comment by SashaWeinstein** [comment]
Ok great thanks Te I am very confused haha

**Comment by td928** [comment]
Hey @AmandaDoyle  before I am heading down a completely wrong path here. I am adding in the pct and pct_moe for 
HUPRt but they are all null in the source data. Just making sure this is expected.

**Comment by td928** [comment]
okay then I am a little confused if we are going with the units affordable source file then we will only have one year (2019) and pct is always 100. Also I just noticed the ami source file won't have race breakdown.

**Comment by AmandaDoyle** [comment]
That's right that there will only be pct and pct moe for 1519 data, and yes there is no race breakdown.

**Comment by td928** [comment]
> That's right that there will only be pct and pct moe for 1519 data, and yes there is no race breakdown.

okay so 0812 would have race breakdown and null pct and pct_moe and 1519 would be what you said? @AmandaDoyle

**Comment by AmandaDoyle** [comment]
I recognize that this isn't the cleanest.  We need to get something to OSE asap.
Goal: Add in percent and percent moe field for units_payrent_1519 - data comes from units affordable to ami.
It is irrelevant if we add in percent and percent moe field for units_payrent_1519 by subgroup or for percent and percent moe field for units_payrent_0812 fields or not, as there is no data or use case for these fields.
Given that we know that units_payrent_1519_pct is 100 for all values we could do a hotfix and hardcode it in until we develop a more elegant solution.  percent moe field is null.

**Comment by td928** [comment]
Okay great I think I was thinking along the same line then with hard coding that one column and then leave the rest. I will have a PR for this soon. Thank you!
