### ISSUE TITLE
Area within historic district

### ISSUE THREAD

**Issue by SashaWeinstein** [NYCPlanning/db-equitable-development-tool#27]
I will start working on this using geopandas to do aggregation

**Comment by AmandaDoyle** [comment]
Description 
- Using data from [open data](https://data.cityofnewyork.us/Housing-Development/Historic-Districts/xbvj-gfnw) compute the area of each PUMA, Borough, and City that is in a historic district.
- Split historic district boundaries by PUMA and Borough boundaries the sum area within geographic area
- Calculate percent by dividing the area in a historic district by the total area of the geography

**Comment by SashaWeinstein** [comment]
Will import the data from data library as a .csv as this is easiest to load into geopandas

**Comment by SashaWeinstein** [comment]
I adopted bash code from the `bash/config.sh` in the `db-cpdb` repo to load in `.env` files. My implementation lives in `/ingest/data_library` and differs in two ways:
1. The cpdb code allows for multiple .env files to be loaded as it uses a `.env` and `version.env`. EDDT only has one `.env` currently so it's `config.sh` can only read one.
2. The cpdb code has this `sed 's/#.*//g'` pipe that as far as I can tell is there to clean out comments. My .env files don't have comments and I don't know why they would so I left this out. If I'm misunderstanding the role of this sed command or there is good reason to allow .env files to have comments then this pipe can be added again

**Comment by SashaWeinstein** [comment]
Not sure where to get PUMA boundaries, found download at https://www.census.gov/cgi-bin/geo/shapefiles/index.php?year=2010&layergroup=Public+Use+Microdata+Areas and saving to `/resources` folder but there may be a better way

**Comment by SashaWeinstein** [comment]
Getting this error message when summing areas

UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

Not sure how to interpret, going forward on analysis and hopefully CRS issues are easy to correct afterwards

**Comment by SashaWeinstein** [comment]
Pushed code in jupyter notebook that iterates through PUMAs and calculates fraction of total area within historic district in each. When I checked numbers it seemed that the PUMA in south west manhattan (3801) had too low a fraction. Just realizing now that issue may be clipping PUMAs to shoreline, when I plotted PUMA dataset the boundaries weren't clipped to shoreline. Next step is find PUMA boundaries that are clipped to shoreline. Then incorporate this code into .py files

**Comment by levysamu** [comment]
I'm working on cleaning up the data dictionary and noticed something surprising in the current definition for this indicator (copied below). It is saying that we included historic districts that were denied designation or overturned. Is that true? If it is, why did we do that?

> Area within a historic district. All designated historic districts or areas under consideration for historic district designation (i.e. calendared) by the New York City Landmarks Preservation Commission (LPC), including items that may have been **denied designation or overturned**.
