### ISSUE TITLE
Process New Source Data 

### ISSUE THREAD

**Issue by mbh329** [NYCPlanning/db-equitable-development-tool#317]
We need to process the source data that was sent so that it matches previous source data version with limited changes to the code which we decided would be the path of least resistance. The following files require some sort of processing manually in xlsx:

- [x] COVID Deaths by race and PUMA_20230109.xlsx
- [x] DOHMH_death rate and overdose.xlsx
- [x] DOHMH_diabetes and self reported health.xlsx
- [x] EDDE - Math and ELA & Grad - 2022.csv
- [ ] EDDE_2023_Updates_transportation.xlsx - waiting for new data from DCP Transportation
- [x] Equitable Development Data Tool - NYCHA - 1-27-2023 Final.xlsx

**Comment by damonmcc** [comment]
closing in favor of [primary data update issue](https://github.com/NYCPlanning/db-equitable-development-tool/issues/312)
