### ISSUE TITLE
Ingest HVS Data

### ISSUE THREAD

**Issue by SashaWeinstein** [NYCPlanning/db-equitable-development-tool#4]
Now that PUMS ingestion is set up the next step in ingestion is HVS data. This data will be harder to convert to pandas-readable tabular format. My process to calculate variance involves starting with HVS data so this is highest priority.

**Comment by SashaWeinstein** [comment]
Realizing now that Baiyue wrote code to ingest HVS that takes advantage of the STATA import program posted on the HVS site. Looking through that on google collab now

**Comment by SashaWeinstein** [comment]
I've read over Baiyue's code and I think I understand what it does. He uses the occupant data and we want the building-level data so that will need to be changed but otherwise his approach should work pretty well

**Comment by AmandaDoyle** [comment]
@SashaWeinstein  Following up on this and documenting from our conversation last week.  The geographic field is the `Sub-Borough Area` field, which is the same as PUMAs.

**Comment by SashaWeinstein** [comment]
Awesome, thanks for documenting this

**Comment by SashaWeinstein** [comment]
We know HVS ingestion was successful because our calculation of total occupied housing units and associated standard error matches the results from page 47 of [official HVS guide to calculating variances](https://www2.census.gov/programs-surveys/nychvs/technical-documentation/variances/2017-NYCHVS-Guide-to-Estimating-Variances.pdf)
