### ISSUE TITLE
Automated Testing

### ISSUE THREAD

**Issue by SashaWeinstein** [NYCPlanning/db-equitable-development-tool#6]
I wrote some functions for validating the data from the PUMS GET request. Currently I call these manually when in the function to make the GET request. They should become proper automated tests eventually. 
The approach for automated testing I know best is pytest which is easy to call in a github workflow for CI/CD. Is there a reason to go with another testing approach @AmandaDoyle?

**Comment by AmandaDoyle** [comment]
@SashaWeinstein  No, that fits into our logic, so go with pytest.  Max also has an interest in automated testing so next week we can see if he has any other ideas.

**Comment by SashaWeinstein** [comment]
ok great!

**Comment by SashaWeinstein** [comment]
I have a github actions question I want to document as I don't know best practice for the situation. 

The two directories of `logs/` and `data/` are used in the ingestion process. They contain logs produced by the python logging module and the PUMS/HVS data cached as .pkl files respectively. I chose to ignore them in git because logs are just for debugging and pushing data uses space in the repo. 

But when I added the first automated tests they were failing because they were looking for directories that weren't there. The best way forward as I was working through the workflow syntax was to add this step
```
    - name: Make Logs Dir
      run: |
        mkdir logs/
        mkdir data/
```

The approach keeps the public repo clean and focused on actual source code while allowing tests to run as they do on my local machine. However it feels like a quick patch because more changes are made to the file organization then this workflow will have to be changed as well. 

Another approach I was thinking about was to push the two directories but none of their contents. This would make the repo harder to navigate but would make it easier to run actions. It would also be easier for someone to pull down the repo and run the code right away. @AmandaDoyle curious if you have thoughts about best practice

**Comment by SashaWeinstein** [comment]
As I'm thinking maybe the solution is logic in the python code to check for the `logs/` and `data/` directories and make them if they aren't there? That would allow public repo to stay clean while making it easy to clone and run and also easy to test on a github action VM

**Comment by AmandaDoyle** [comment]
@SashaWeinstein best practice is to have it so that someone can pull down the repo and run the code right away.  Adding logic to the python code to add empty directories is the better of the two options
