### ISSUE TITLE
Access to open space

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-equitable-development-tool#84]
Description: Percent of residents within walking distance to a park

Where we Live Figure 5.69: These areas are within a .25 mile and .5-mile walking distance of park entrances. Parks under 6 acres are assigned a .25 mile walk area, larger parks are assigned a .5-mile walk area. The analysis includes all publicly accessible open space in NYC, including plazas.

Logic:

Source(s): https://nyco365.sharepoint.com/:x:/r/sites/NYCPLANNING/civic-engagement-studio/_layouts/15/Doc.aspx?sourcedoc=%7BE8F466AD-5484-4628-AB9E-7AB6EBDC5A52%7D&file=Park_Access.csv&action=default&mobileredirect=true&cid=c563e44a-3bc8-4f8d-912d-39c3b8b261ae

Year(s):
- [ ] 2019 / 2020

Geographies:
    - [ ] PUMA
    - [ ] Borough
    - [ ] City

Race and ethnicity breakdown:  No
Denominator:

SME:

Questions:

Roadblocks:
Field name convention: `access_openspace`

**Comment by levysamu** [comment]
We have this at the [PUMA geography](https://nyco365.sharepoint.com/:x:/r/sites/NYCPLANNING/civic-engagement-studio/_layouts/15/Doc.aspx?sourcedoc=%7BE8F466AD-5484-4628-AB9E-7AB6EBDC5A52%7D&file=Park_Access.csv&action=default&mobileredirect=true&cid=c563e44a-3bc8-4f8d-912d-39c3b8b261ae). Need to aggregate PUMAs into borough and city level.

Year:
- Park layer = 2018
- Population data = 2020 Census

Numerator is population (block level Census data) with centroids inside walkshed geography produced by DPR. Denominator is the total 2020 PUMA population.
