### ISSUE TITLE
Variance of a Median Calculation for Age in Buckets

### ISSUE THREAD

**Issue by SashaWeinstein** [NYCPlanning/db-equitable-development-tool#9]
We talked about how to get median age when age is put into buckets in our meeting today. Next step is to look at population factfinder repo which does "median of a median" calculation and might be instructive.

**Comment by SashaWeinstein** [comment]
I looked at population factfinder's median calculations this morning. I have some questions on context.

1. On PFF I only see one median calculation, which is for age. I don't see any number for which a a "median of medians" would be used. Where in population factfinder does it take a median of medians?
2. What mathematical formula does `factfinder/median.py` implement? Most variables are named as just `L` or `B` which makes it hard to see what the code is doing.

I'm assuming Erica is the best person to talk to about this if we can't find answers to these questions?

**Comment by AmandaDoyle** [comment]
@SashaWeinstein 
Answers:
1. I may have been mistaken and we didn't actually end up needing to implement a median of medians calculation.
2. What's going on in `factfinder/median.py` is documented [here](https://github.com/NYCPlanning/db-factfinder/wiki/Median-calculations#medians).  I think L is the estimate of count in range and B is the cumulative count

**Comment by SashaWeinstein** [comment]
Awesome thanks for the link to the wiki. I looked to the documentation generated by pydoc but didn't think to look at the wiki.

**Comment by SashaWeinstein** [comment]
I'm meeting with Erica on Monday to review the issue where our numbers don't match the HVS guide to calculating variances

**Comment by SashaWeinstein** [comment]
Now that census told us to use `interval.type = "quantile"` we  can start calculating variances of medians on `Find-Variance-of-Median` branch

**Comment by SashaWeinstein** [comment]
Actually opening a new branch, `9-Add-Median-Age`

**Comment by SashaWeinstein** [comment]
Have class to calculate median age of entire population and by racial group. Not sure how age buckets come into play, but hopefully the median ages I have are what we need or a step forward
